travis:
  secure:
    BINSTAR_TOKEN: Ofaso3VM2yX9uuiSLwQQKZmFbQs6n+PdLNQZ02jg0u6wSHMSfsF540+45Xfx/ob0StBpX2DLMKVACGtlTcXG6bN0TFIzHuGSm2jWiFGbPoQdvWNqaeADls/iW7wLhdIkCFmhj+XzDKbvSYbTGrHd3pQzMVqvqtJZxBKAZW18zQXhrsXbYl+tRR9SIFydTwyvcCOwt7MG9eGa9FnQj0EnslYyKXEoE8wC/h74E88IeIrRW9Sm/E2zMs77b3giAjR1T7uhZfNGQFJDnzVsse2p7BYA2EgMo5PCe18SdguEALSsCMZeBpMayOfKtqmhQFGihGGDHi7ES+4oL7W/4QcLfQ6ZPSdQzGmKPk+WlUO1OirFNOgRuSE0n0aAEPUnDVAqQTGMU0ExR5QnoEODaGCzv4jDn3Gr/R2yV82DXSnYDSmBFUzCTeRapxFjZOJA3xfS8h0RX6tdosnWH/Hjaebi5R8mYYSZYc5h8BOlDmgp0TUVUfyUgn6N0YX3BWKWhKwEbl9PoQl0+HeFQUz2JrQCr7T6JIZElr1b40ZT+4+dtvJLdUMVunUvKp1ycB7uPoJkla16Soa2H275Mo0ZEtekKvylTFvBBoKzjub/oUBMYUnJApH+2OBBNwMMWvW9QNs7YzD6FHlk005EihnaV0/nC5yJ7MTh5s20n7A0d2MXpdo=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
