travis:
  secure:
    BINSTAR_TOKEN: WyULPOlaWGIwklM4gtgBit3EBOO6v+7lKDCPUbqqePZaZhAGySsOMMmJkZ0VxNfrCuf+CAyQX4rHS/nja9lY2KXHvZ9EeBmzMHgai8kWBGTpZLIlUJhDeDXuyUHN2WvKS1LA0f8tyVMtULrxQ2fmJ0I0wWYFCc0X1liCnR2YYOmmELspMSRBp8/Dx6Z9vIBLWrmV/fbrM3VMwW/SpuEvuCq8grIT8Um1oaN/o1KHafznc69n0KT7SX4Nf+KMHqNf2s2A9YXJKC5z5sXPoMHCe6vUc8UizqIT2GaGbUnkm0Z7E93RsEXd/D0OhR9W1hHXoxHVwzc5AChmNcFJcPuGCuew/DWx7bsLN6xdpzFrlEg7oXZitVfzq9zLipeV5n2Qnc9/NaH2fK9mFGy4LPq9MSKbTIgkt91kdvuEeoKH3UKGdoKEriRohaKcMGlHjTLmJosz1HRJ2HXHRLK3VvubfN/CPmwKbRPQ6P51ACX7KdA7rdvV6D7ATYX0xArSxWS0fjpdwCGGrgQuLkpqdiEZ2johjRFwKJ5+Zbrl4bYvTlOwR3DBssnJf/yeL1e5TM8mJCn5jeGunzi1VjhuXXZi372tL4lCasgh5Z+FrDlgU6/aJ/n9CR2bQzooKBVJi1G8hakrCeKpkWR19fpsjfVAZ4/vXh8HB4tzFsVjVIzCWc8=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
