travis:
  secure:
    BINSTAR_TOKEN: inPbMDbc+HNYaw8aztn1Df2I+JaISzFRTDrUHoiCjehxtJdwE4rqT6jsg8x4GOniHXEtyPryEAhBh5bKeutR+BTYlBrGxBZ+Qe8m8jijKDt7KYRfHUa5qa0shVJxLTEq2YwSfPz8fLPwxmNgkeIyKbBrFF6BpAntbk+2sWE3YFrQnvMwWa1WdGoGEN6qXeGBElfWkuEKGxldpSs5YcN/PqeaiyeXd8eREhBbdRDnQZKR46BozdBvqMwR70lguA8sUSSMKVcTE63H6QjDNoJLQTfMFcbNmT2zS08bHcz7q+J5UOU87MhB70xQNxbhimSkj3oMw+RHAnLo/LzvjB51+eGEGUO9wySz8a/SM/cLHK2mbkd6z6ZxjGJRGRyz92x07XsMuDQIPjX8d+HUTuHL6b21EGxyMy4o8fa3/VE9ZQ7P/myYruRffJrLU0s8FgpsODedd+DB7JtEyEyaKIZrRhkelgW6jgJAm/5knEPKUFONTiTma4X2IslL9iNThSbNo7wDs2z2ZU0/pgGuaYDKr/jcobhtXmfVgdaP7Zsb2erukSkQCcco+vL/ohNjLNsq5rMDEJyioIe57LMF2EGfxRszmx1M687F/9TTE3G1uzQuVmwY9hEygb41v1Ytb/uk9AGHYoE0hUbmjWKGF0tG9vjAkEMBQClxy05VIeRHFDo=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
